# Site settings
title: Sean Hickey
email: shickey@blakeschool.org
description: > 
  Computer science teacher and technology specialist
  at The Blake School, Minneapolis, MN.
url: "http://shickey.github.io" # the base hostname & protocol for your site
twitter: seanhic
github:  shickey

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['scripts']
